//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basculeManger
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon
    {
        public int id { get; set; }
        public Nullable<int> id_vent { get; set; }
        public Nullable<decimal> poids { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual vente vente { get; set; }
    }
}
