//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basculeManger
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrat
    {
        public int id { get; set; }
        public Nullable<int> id_entrepr { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fine { get; set; }
        public Nullable<int> id_entrepreneur { get; set; }
    
        public virtual entrepreneur entrepreneur { get; set; }
    }
}
