//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basculeManger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbbasculesContext : DbContext
    {
        public dbbasculesContext()
            : base("name=dbbasculesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bon> bons { get; set; }
        public virtual DbSet<caisse> caisses { get; set; }
        public virtual DbSet<camion> camions { get; set; }
        public virtual DbSet<chiffeur> chiffeurs { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<contrat> contrats { get; set; }
        public virtual DbSet<entrepreneur> entrepreneurs { get; set; }
        public virtual DbSet<gerant> gerants { get; set; }
        public virtual DbSet<produit> produits { get; set; }
        public virtual DbSet<vente> ventes { get; set; }
    }
}
